# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-javascript/.eslintrc.yml
# See: https://eslint.org/docs/user-guide/configuring/
# The code style defined in this file is the official standardized style to be used in all Arduino projects and should
# not be modified.

extends:
  - airbnb-base
  - prettier
  - plugin:jsonc/recommended-with-json
  - plugin:jsonc/prettier
ignorePatterns:
  - "**/package-lock.json"
parserOptions:
  ecmaVersion: latest
plugins:
  - jsonc
rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "**/tests/*.js"
  import/no-unresolved:
    - error
    - ignore:
        # Workaround for https://github.com/import-js/eslint-plugin-import/issues/1810
        - yeoman-test
  jsonc/key-name-casing:
    - warn
    - camelCase: true
  max-len:
    - error
    - code: 180
  no-console: "off"
  no-underscore-dangle: "off"
