# See: https://docs.codecov.com/docs/codecovyml-reference

comment:
  # See: https://docs.codecov.com/docs/pull-request-comments#behavior
  behavior: new
  # See: https://docs.codecov.com/docs/pull-request-comments#requiring-changes
  require_changes: false
