# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-prettier-formatting-task.md
name: Check Prettier Formatting

# See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-prettier-formatting-task.ya?ml"
      - "Taskfile.ya?ml"
      - "tools.go"
      - "**/.npmrc"
      - "**/.prettierignore"
      - "**/.prettierrc*"
      - "go.mod"
      - "go.sum"
      # Prettier-covered file patterns are defined by:
      # https://github.com/github-linguist/linguist/blob/master/lib/linguist/languages.yml
      # CSS
      - "**.css"
      - "**.wxss"
      # PostCSS
      - "**.pcss"
      - "**.postcss"
      # Less
      - "**.less"
      # SCSS
      - "**.scss"
      # GraphQL
      - "**.graphqls?"
      - "**.gql"
      # handlebars
      - "**.handlebars"
      - "**.hbs"
      # HTML
      - "**.mjml"
      - "**.html?"
      - "**.html.hl"
      - "**.st"
      - "**.xht"
      - "**.xhtml"
      # Vue
      - "**.vue"
      # JavaScript
      - "**.flow"
      - "**._?jsb?"
      - "**.bones"
      - "**.cjs"
      - "**.es6?"
      - "**.frag"
      - "**.gs"
      - "**.jake"
      - "**.jscad"
      - "**.jsfl"
      - "**.js[ms]"
      - "**.[mn]js"
      - "**.pac"
      - "**.wxs"
      - "**.[xs]s?js"
      - "**.xsjslib"
      # JSX
      - "**.jsx"
      # TypeScript
      - "**.ts"
      # TSX
      - "**.tsx"
      # JSON
      - "**/.eslintrc"
      - "**.json"
      - "**.avsc"
      - "**.geojson"
      - "**.gltf"
      - "**.har"
      - "**.ice"
      - "**.JSON-tmLanguage"
      - "**.mcmeta"
      - "**.tfstate"
      - "**.topojson"
      - "**.webapp"
      - "**.webmanifest"
      - "**.yyp?"
      # JSONC
      - "**/.babelrc"
      - "**/.jscsrc"
      - "**/.js[hl]intrc"
      - "**.jsonc"
      - "**.sublime-*"
      # JSON5
      - "**.json5"
      # Markdown
      - "**.mdx?"
      - "**.markdown"
      - "**.mk?down"
      - "**.mdwn"
      - "**.mkdn?"
      - "**.ronn"
      - "**.workbook"
      # TOML
      - "**/Cargo.lock"
      - "**/Cargo.toml.orig"
      - "**/Gopkg.lock"
      - "**/Pipfile"
      - "**/pdm.lock"
      - "**/poetry.lock"
      - "**.toml"
      # YAML
      - "**/.clang-format"
      - "**/.clang-tidy"
      - "**/.gemrc"
      - "**/glide.lock"
      - "**.ya?ml*"
      - "**.mir"
      - "**.reek"
      - "**.rviz"
      - "**.sublime-syntax"
      - "**.syntax"
  pull_request:
    paths:
      - ".github/workflows/check-prettier-formatting-task.ya?ml"
      - "Taskfile.ya?ml"
      - "tools.go"
      - "**/.npmrc"
      - "**/.prettierignore"
      - "**/.prettierrc*"
      - "go.mod"
      - "go.sum"
      # CSS
      - "**.css"
      - "**.wxss"
      # PostCSS
      - "**.pcss"
      - "**.postcss"
      # Less
      - "**.less"
      # SCSS
      - "**.scss"
      # GraphQL
      - "**.graphqls?"
      - "**.gql"
      # handlebars
      - "**.handlebars"
      - "**.hbs"
      # HTML
      - "**.mjml"
      - "**.html?"
      - "**.html.hl"
      - "**.st"
      - "**.xht"
      - "**.xhtml"
      # Vue
      - "**.vue"
      # JavaScript
      - "**.flow"
      - "**._?jsb?"
      - "**.bones"
      - "**.cjs"
      - "**.es6?"
      - "**.frag"
      - "**.gs"
      - "**.jake"
      - "**.jscad"
      - "**.jsfl"
      - "**.js[ms]"
      - "**.[mn]js"
      - "**.pac"
      - "**.wxs"
      - "**.[xs]s?js"
      - "**.xsjslib"
      # JSX
      - "**.jsx"
      # TypeScript
      - "**.ts"
      # TSX
      - "**.tsx"
      # JSON
      - "**/.eslintrc"
      - "**.json"
      - "**.avsc"
      - "**.geojson"
      - "**.gltf"
      - "**.har"
      - "**.ice"
      - "**.JSON-tmLanguage"
      - "**.mcmeta"
      - "**.tfstate"
      - "**.topojson"
      - "**.webapp"
      - "**.webmanifest"
      - "**.yyp?"
      # JSONC
      - "**/.babelrc"
      - "**/.jscsrc"
      - "**/.js[hl]intrc"
      - "**.jsonc"
      - "**.sublime-*"
      # JSON5
      - "**.json5"
      # Markdown
      - "**.mdx?"
      - "**.markdown"
      - "**.mk?down"
      - "**.mdwn"
      - "**.mkdn?"
      - "**.ronn"
      - "**.workbook"
      # TOML
      - "**/Cargo.lock"
      - "**/Cargo.toml.orig"
      - "**/Gopkg.lock"
      - "**/Pipfile"
      - "**/pdm.lock"
      - "**/poetry.lock"
      - "**.toml"
      # YAML
      - "**/.clang-format"
      - "**/.clang-tidy"
      - "**/.gemrc"
      - "**/glide.lock"
      - "**.ya?ml*"
      - "**.mir"
      - "**.reek"
      - "**.rviz"
      - "**.sublime-syntax"
      - "**.syntax"
  workflow_dispatch:
  repository_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Task
        run: |
          go \
            install \
              github.com/go-task/task/v3/cmd/task

      - name: Format with Prettier
        run: |
          task \
            general:format-prettier

      - name: Check formatting
        run: |
          git \
            diff \
            --color \
            --exit-code
