# foobar
on:
  push: ~
  pull_request: ~

jobs:
  foo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - run: echo hello > foo.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Updated themes
          title: Update themes
          branch: themes/themes-update
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
