on: push
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version-file: pyproject.toml

      - name: Install Poetry
        run: |
          pipx install \
            --python "$(which python)" \
            "$( \
              yq \
                --input-format toml \
                --output-format yaml \
                '.project.optional-dependencies.pipx[] | select(test("^poetry=="))' \
                < "pipx-data/pyproject.toml" \
            )"

      - run: |
          poetry --version
