name: Hello
#
on:
  push: ~
  pull_request: ~

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Send unit tests coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ vars.CODECOV_TOKEN }}
