# Source: https://github.com/per1234/.github/blob/main/workflow-templates/test-javascript-jest-task.md
name: Test JavaScript

on:
  push:
    paths:
      - ".github/workflows/test-javascript-jest-task.ya?ml"
      - ".github/.?codecov.ya?ml"
      - "dev/.?codecov.ya?ml"
      - "etc/generator-kb-document-configuration-schema.json"
      - "etc/generator-kb-document-prompts-configuration-schema.json"
      - ".?codecov.ya?ml"
      - "**/jest.config.[cm]?js"
      - "**/jest.config.json"
      - "**/jest.config.ts"
      - "**/package.json"
      - "**/package-lock.json"
      - "Taskfile.ya?ml"
      - "tests/testdata/**"
      - "**/tsconfig.json"
      - "**.[jt]sx?"
  pull_request:
    paths:
      - ".github/workflows/test-javascript-jest-task.ya?ml"
      - ".github/.?codecov.ya?ml"
      - "dev/.?codecov.ya?ml"
      - "etc/generator-kb-document-configuration-schema.json"
      - "etc/generator-kb-document-prompts-configuration-schema.json"
      - ".?codecov.ya?ml"
      - "**/jest.config.[cm]?js"
      - "**/jest.config.json"
      - "**/jest.config.ts"
      - "**/package.json"
      - "**/package-lock.json"
      - "Taskfile.ya?ml"
      - "tests/testdata/**"
      - "**/tsconfig.json"
      - "**.[jt]sx?"
  workflow_dispatch:
  repository_dispatch:

jobs:
  run-determination:
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      result: ${{ steps.determination.outputs.result }}
    steps:
      - name: Determine if the rest of the workflow should run
        id: determination
        run: |
          RELEASE_BRANCH_REGEX="refs/heads/[0-9]+.[0-9]+.x"
          # The `create` event trigger doesn't support `branches` filters, so it's necessary to use Bash instead.
          if [[
            "${{ github.event_name }}" != "create" ||
            "${{ github.ref }}" =~ $RELEASE_BRANCH_REGEX
          ]]; then
            # Run the other jobs.
            RESULT="true"
          else
            # There is no need to run the other jobs.
            RESULT="false"
          fi

          echo "result=$RESULT" >> $GITHUB_OUTPUT

  test:
    name: test (${{ matrix.project.path }}, ${{ matrix.operating-system }})
    needs: run-determination
    if: needs.run-determination.outputs.result == 'true'
    runs-on: ${{ matrix.operating-system }}
    defaults:
      run:
        shell: bash
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        project:
          - path: .
        operating-system:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Task
        run: |
          go \
            install \
              github.com/go-task/task/v3/cmd/task

      - name: Run tests
        run: |
          task \
            --silent \
            js:test \
            PROJECT_PATH="${{ matrix.project.path }}"

      - name: Send unit tests coverage to Codecov
        if: runner.os == 'Linux'
        uses: codecov/codecov-action@v4
        with:
          # Even though the file is specified via the `file` input. The action still pointlessly searches for the file
          # by default.
          disable_search: true
          fail_ci_if_error: true
          file: ${{ matrix.project.path }}/coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
